# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:18
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=100)),
                ('polemica', models.BooleanField(default=False)),
                ('tramita', models.BooleanField(default=False)),
                ('regime', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('ementa', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('url_materia_integra', models.URLField(blank=True)),
                ('area_impacto', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('dados', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='materias.Materia')),
            ],
        ),
    ]
